"""update tables

Revision ID: e210420d74d4
Revises: 
Create Date: 2019-10-21 17:03:43.313877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e210420d74d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_list_categoryListType', table_name='category_list')
    op.drop_table('category_list')
    op.drop_table('task_queue')
    op.add_column('message_queue', sa.Column('tgUrl', sa.String(), nullable=False))
    op.create_index(op.f('ix_message_queue_tgUrl'), 'message_queue', ['tgUrl'], unique=True)
    op.alter_column('transaction', 'taskId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['advId'], ['username'])
    op.create_foreign_key(None, 'transaction', 'user', ['affId'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['advId'], ['id'])
    op.create_foreign_key(None, 'transaction', 'user', ['affId'], ['id'])
    op.alter_column('transaction', 'taskId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_message_queue_tgUrl'), table_name='message_queue')
    op.drop_column('message_queue', 'tgUrl')
    op.create_table('task_queue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('categoryListType', sa.VARCHAR(length=32), nullable=False),
    sa.Column('categoryId', sa.INTEGER(), nullable=False),
    sa.Column('offerId', sa.INTEGER(), nullable=False),
    sa.Column('channelId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['category.id'], ),
    sa.ForeignKeyConstraint(['channelId'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['offerId'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_category_list_categoryListType', 'category_list', ['categoryListType'], unique=False)
    # ### end Alembic commands ###
